services:
  - type: web
    name: ai-orchestration
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RATELIMIT_DEFAULT
        value: "100 per day"
      - key: RATELIMIT_STORAGE_URL
        fromService:
          type: redis
          name: ai-orchestration-cache
          property: connectionString
      - key: PASSWORD_SALT
        generateValue: true
    autoDeploy: true

  - type: redis
    name: ai-orchestration-cache
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
