services:
  - type: web
    name: ai-orchestration
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:create_app() --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
