"""สรางตาราง users และ tenants

Revision ID: d6d5b7a70b8d
Revises: 
Create Date: 2025-03-06 23:18:11.641440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d5b7a70b8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tenants', ['name'])
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'tenants', type_='unique')
    # ### end Alembic commands ###
