"""เพม status ในตาราง tenants

Revision ID: d6dc42b1c8d0
Revises: d6d5b7a70b8d
Create Date: 2025-03-06 23:25:59.942110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dc42b1c8d0'
down_revision = 'd6d5b7a70b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'description')
    # ### end Alembic commands ###
